### ISSUE TITLE
编译H5环境会报错，但是不生效

### ISSUE THREAD

**Issue by yourVictor** [andurils/vant-weapp-uniapp#2]
微信小程序是可以的。
但H5会报以下错误
![image](https://user-images.githubusercontent.com/20289879/75618673-c1136e00-5bac-11ea-818e-c679dfd89b0b.png)

**Comment by andurils** [comment]
page.json 有没有注册组件 globalStyle节点下

`
"globalStyle": { 
		"usingComponents": { //这里为方便，全局引入了所有组件，也可以在某个page下单独引用某个组件  
			"van-button": "/wxcomponents/vant/button/index",
			 ……组件引入
                         ……
		}
	},
`
